# Generated by Django 5.2 on 2025-05-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wishlist/'),
        ),
    ]
