# Generated by Django 5.2 on 2025-06-19 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_image_alter_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='dateAdded',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='image',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='stockStatus',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='unitPrice',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='userId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.user'),
        ),
    ]
